import styles from "./page.module.css";

export default function Page() {
  return (
    <div className={styles.main}>
      <h1>FAQ</h1>

      <ol type="1" className={styles.mainList}>
        <li style={{fontSize: "2rem"}}>
          <h3>Can Outfit Anyone AI handle various clothing styles?</h3>
          <ul>
            <li className={styles.indent}>
              <p>
                Yes, Outfit Anyone AI is designed to adapt to a wide range of
                clothing styles, from casual to formal, ensuring a versatile
                try-on experience.
              </p>
            </li>
          </ul>
        </li>
        <li style={{fontSize: "2rem"}}>
          <h3>Is Outfit Anyone AI suitable for all body types?</h3>
          <ul>
            <li className={styles.indent}>
              <p>
                {" "}
                Absolutely! Our platform is built to accommodate different body
                types, offering a personalized and inclusive virtual try-on
                experience.
              </p>
            </li>
          </ul>
        </li>
        <li style={{fontSize: "2rem"}}>

              <h3>How realistic are the try-ons with Outfit Anyone AI?</h3>
          <ul>
            <li className={styles.indent}>
              <p>
                Outfit Anyone AI provides highly realistic try-ons using
                advanced AI that meticulously adapts clothing to the users body
                and the chosen outfits style and texture.
              </p>
            </li>
          </ul>
        </li>
        <li style={{fontSize: "2rem"}}>
          <strong>
            Can I use Outfit Anyone AI for animation character design?
          </strong>
          <ul>
            <li className={styles.indent}>
              <p>
                Yes, Outfit Anyone AI extends its capabilities to animation
                characters, allowing users to explore and create fashion for
                virtual characters.
              </p>
            </li>
          </ul>
        </li>
        <li style={{fontSize: "2rem"}}>
          <h3>Do you offer an API for Outfit Anyone AI?</h3>
          <ul>
            <li className={styles.indent}>
                <p>              We do not offer an API for Outfit Anyone AI at this time. Our team
              is focused on enhancing the platforms core features and may
              consider API availability in the future.</p>
            </li>
          </ul>
        </li>
        <li style={{fontSize: "2rem"}}>
            <h3>            Can I use the images generated by Outfit Anyone AI for commercial
            purposes?</h3>
          <ul>
            <li className={styles.indent}>
    <p>
    If you need to use the generated images for commercial purposes,
              you must ensure that the model and garment do not violate any
              other rights. This website bears no responsibility in such cases.
    </p>
            </li>
          </ul>
        </li>
      </ol>
    </div>
  );
}
