import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const font = Poppins({
  weight: ["100", "200", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Replicate API Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={font.className}>
          <Header></Header>
          {children}
          <Footer></Footer>
        </body>
      </html>
  );
}
